#!/usr/bin/env bash
# Demonstrate runtime producer-key rotation via the admin API.
#
# Stage 4 moved the producer-key trust store to SQLite with admin
# CRUD matching the reference TL's /internal/v1/producer-keys
# swagger. This script exercises the full rotation surface:
#
#   1. GET    /internal/v1/producer-keys/ra/ans-ra-local   (before)
#   2. POST   /internal/v1/producer-keys                   (register a new key)
#   3. GET    /internal/v1/producer-keys/ra/ans-ra-local   (after — both keys)
#   4. GET    /internal/v1/producer-keys/{key_id}          (fetch the new one)
#   5. DELETE /internal/v1/producer-keys/{key_id}          (revoke the new one)
#   6. GET    /internal/v1/producer-keys/ra/ans-ra-local   (shows revoked row too)
#
# The new key uses a fresh EC P-256 keypair generated by openssl — the
# private half is discarded, since the whole point of this script is
# to show the admin surface accepts a key and persists it. A real
# rotation would publish the public half here and keep the private
# half in the RA's KeyManager.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

require_cmd openssl
require_cmd jq

# ----- 0. make sure the TL is up -----
if ! curl -sSf "$TL_URL/v2/admin/health" >/dev/null 2>&1; then
  fail "ans-tl isn't reachable at $TL_URL — run scripts/demo/start.sh first"
fi

# ----- 1. list current keys -----
header "1. Before: GET /internal/v1/producer-keys/ra/ans-ra-local"
curl_tl GET "/internal/v1/producer-keys/ra/ans-ra-local" >/dev/null

# ----- 2. generate a fresh key and register it -----
header "2. Generate + register a fresh producer key"
KEYDIR="$DATA/rotate-keys"
mkdir -p "$KEYDIR"
KEYID="ra-rotate-$(openssl rand -hex 3)"
openssl ecparam -name prime256v1 -genkey -noout -out "$KEYDIR/priv.pem" 2>/dev/null
openssl ec -in "$KEYDIR/priv.pem" -pubout -out "$KEYDIR/pub.pem" 2>/dev/null
# The keypair is disposable — the whole registration only cares about
# the public half. Private key stays on disk for the lifetime of the
# script only; wiped on the next start.sh --clean.
PUB_PEM=$(cat "$KEYDIR/pub.pem")
VALID_FROM=$(date -u +%Y-%m-%dT%H:%M:%SZ)
# 90-day expiry — tight enough to look realistic, wide enough that
# the demo doesn't expire before anyone reads the output.
EXPIRES_AT=$(date -u -v+90d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null \
  || date -u -d "+90 days" +%Y-%m-%dT%H:%M:%SZ)

REQ=$(jq -n \
  --arg keyId "$KEYID" \
  --arg raId "ans-ra-local" \
  --arg pem "$PUB_PEM" \
  --arg validFrom "$VALID_FROM" \
  --arg expiresAt "$EXPIRES_AT" \
  '{key_id: $keyId, ra_id: $raId, algorithm: "ES256",
    public_key_pem: $pem, valid_from: $validFrom, expires_at: $expiresAt,
    metadata: {environment: "local", region: "na"}}')
curl_tl POST "/internal/v1/producer-keys" "$REQ" >/dev/null

# ----- 3. confirm the new key is listed -----
header "3. After register: GET /internal/v1/producer-keys/ra/ans-ra-local"
curl_tl GET "/internal/v1/producer-keys/ra/ans-ra-local" >/dev/null

# ----- 4. fetch the new key by ID -----
header "4. GET /internal/v1/producer-keys/$KEYID"
curl_tl GET "/internal/v1/producer-keys/$KEYID" >/dev/null

# ----- 5. revoke the new key -----
header "5. DELETE /internal/v1/producer-keys/$KEYID"
curl_tl DELETE "/internal/v1/producer-keys/$KEYID" >/dev/null

# ----- 6. confirm status=revoked is visible in the list -----
header "6. After revoke: GET /internal/v1/producer-keys/ra/ans-ra-local"
curl_tl GET "/internal/v1/producer-keys/ra/ans-ra-local" >/dev/null

ok "producer-key rotation demo complete (keyId=$KEYID is now revoked)"
