// Package event defines the V1 Transparency Log event envelope and the
// canonicalization / leaf-hash rules the TL and its verifiers rely on.
//
// The schema mirrors the reference TL's V1 event envelope
// byte-for-byte. Shape is a contract — any deviation breaks offline
// verifiers.
//
// Life-cycle of an envelope:
//
//  1. Producer (the RA) constructs an Event, JCS-canonicalizes it, and
//     computes a detached JWS over the canonical bytes. The Event plus
//     the detached JWS travel to the TL as the POST body + X-Signature
//     header respectively.
//  2. On receipt, the TL verifies the producer signature against the
//     raw body, then wraps the Event in an Envelope{Payload{LogID,
//     Producer{Event, KeyID, Signature}}}.
//  3. The TL calls SigningInput() to get the canonical bytes of the
//     envelope while its outer Signature is still empty, and produces
//     a detached JWS over those bytes with its own key.
//  4. The TL assigns the resulting JWS to Envelope.Signature.
//  5. LeafBytes() returns the JCS-canonical bytes of the now-complete
//     envelope; LeafHash() returns SHA-256(0x00 || LeafBytes()) per
//     RFC 6962 §2.1, matching what Tessera computes internally.
//
// The `omitempty` tag on Signature is load-bearing: step 3's JCS sees
// no `signature` key in the envelope (because it's empty); step 5's
// JCS sees the now-populated signature key. A verifier who receives
// the full leaf bytes recovers the TL's signing input by stripping
// `signature` back to empty and re-canonicalizing, then verifies the
// detached JWS over those bytes.
package event

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	anscrypto "github.com/godaddy/ans/internal/crypto"
)

// SchemaVersion pins the envelope version. "V2" because our V2 RA
// API emits the richer attestation shape (unified identityCerts[] /
// serverCerts[] arrays, typed dnsRecordsProvisioned[], prefixed
// fingerprints). The reference ships V1 (and historically V0) with
// singleton certs + map-based DNS records; our TL can still serve
// those schemas at `/v1/log/schema/V0` + `/v1/log/schema/V1` for
// backwards-compat lookups, but every envelope we *produce* carries
// `schemaVersion: "V2"`. JCS is byte-precise so the capitalisation
// and value have to be exact.
const SchemaVersion = "V2"

// Type classifies an ANS lifecycle event. Values match the reference
// RA's `EventType` enum. The TL accepts any string (it just parses
// and stores), but the producer side is authoritative for which
// tokens are legitimate event types on the wire.
type Type string

// V2 lane uses the same four-value eventType enum as V1: the RA
// emits a single terminal leaf per lifecycle transition, and the TL
// derives WARNING / EXPIRED at read time from the attested cert
// expiry. No intermediate (AGENT_REGISTRATION / DOMAIN_VALIDATION /
// AGENT_ACTIVE) events exist on either lane.
//
// What V2 changes relative to V1 is the envelope's attestation
// *shape* — singleton + rotation-array cert pairs collapse into
// `identityCerts[]` / `serverCerts[]`, and the DNS-records map
// becomes a typed `dnsRecordsProvisioned[]` array — NOT the event
// type enum. See the CLAUDE.md "Event envelope attestations shape"
// deviation row.
const (
	// TypeAgentRegistered — agent transitioned to ACTIVE (certs
	// issued + DNS provisioned + domain validated). Single terminal
	// "registration complete" leaf; emitted once at verify-dns.
	TypeAgentRegistered Type = "AGENT_REGISTERED"

	// TypeAgentRenewed — a server-certificate renewal cycle
	// completed. Emitted once per renewal.
	TypeAgentRenewed Type = "AGENT_RENEWED"

	// TypeAgentRevoked — the agent was revoked (by the owner or
	// administratively). Terminal.
	TypeAgentRevoked Type = "AGENT_REVOKED"

	// TypeAgentDeprecated — the agent was superseded by a newer
	// version and is scheduled for rotation.
	TypeAgentDeprecated Type = "AGENT_DEPRECATED"

	// TypeEquivalenceLink — two registrations share an operational
	// identity. Carries Equivalence in place of Agent / Attestations.
	// See ANS-0 §7 cross-anchor coexistence and the EquivalenceLink
	// struct below.
	TypeEquivalenceLink Type = "EQUIVALENCE_LINK"
)

// IsValid reports whether t is a recognized event type.
func (t Type) IsValid() bool {
	switch t {
	case TypeAgentRegistered,
		TypeAgentRenewed,
		TypeAgentRevoked,
		TypeAgentDeprecated,
		TypeEquivalenceLink:
		return true
	default:
		return false
	}
}

// Envelope is the top-level structure appended to the Merkle tree.
// Byte-for-byte compatible with the reference TL's V1 event envelope.
type Envelope struct {
	Payload       *Payload `json:"payload,omitempty"`
	SchemaVersion string   `json:"schemaVersion,omitempty"`
	Signature     string   `json:"signature,omitempty"` // TL attestation (detached JWS)
	Status        string   `json:"status,omitempty"`
}

// Payload wraps the producer's signed event with a TL-assigned logId.
// The logId is a UUIDv7 generated by the TL on ingest — it is not
// under producer control, and it is what clients use to correlate a
// receipt request to a specific tree position.
type Payload struct {
	LogID    string    `json:"logId"`
	Producer *Producer `json:"producer"`
}

// Producer records the event together with the producer's identity
// and its detached-JWS attestation over the inner Event.
type Producer struct {
	Event     *Event `json:"event"`
	KeyID     string `json:"keyId"`
	Signature string `json:"signature"`
}

// Event is the producer-authored payload. The producer JCS-canonicalizes
// this and signs it; the resulting detached JWS lands in Producer.Signature.
type Event struct {
	AnsID                string            `json:"ansId"`
	AnsName              string            `json:"ansName"`
	EventType            Type              `json:"eventType"`
	Agent                *Agent            `json:"agent,omitempty"`
	Attestations         *Attestations     `json:"attestations,omitempty"`
	Equivalence          *EquivalenceLink  `json:"equivalence,omitempty"`
	ExpiresAt            string            `json:"expiresAt,omitempty"`
	IssuedAt             string            `json:"issuedAt,omitempty"`
	RaID                 string            `json:"raId,omitempty"`
	RenewalStatus        string            `json:"renewalStatus,omitempty"`
	RevocationReasonCode string            `json:"revocationReasonCode,omitempty"`
	RevokedAt            string            `json:"revokedAt,omitempty"`
	Timestamp            string            `json:"timestamp"` // RFC3339, required
}

// EquivalenceLink records that two registrations share an operational
// identity. Recorded under EventType=EQUIVALENCE_LINK; the AnsID at
// the top of the event is the *primary* registration making the
// assertion, and the LinkedAnsID is the *other* registration the
// primary is asserting equivalence with.
//
// The producer signature on the enclosing event is the cryptographic
// link: a verifier reading the event sees the producer (the RA) attest
// that "AnsID and LinkedAnsID resolve to the same operational entity."
// The producer's authority to make that claim derives from the RA's
// position as the registrar of both sides; deployments enforce that
// authority by validating that the asserting controller has authority
// over both registrations before signing.
//
// The reference impl provides the type and validation; emission paths
// and per-deployment authority checks are operator concerns.
type EquivalenceLink struct {
	// LinkedAnsID is the agentId of the linked registration (the one
	// asserted to be the same operational entity as the event's
	// primary AnsID). Required.
	LinkedAnsID string `json:"linkedAnsId"`

	// LinkedAnsName is the linked registration's ANSName when the
	// linked anchor produces one; empty for non-FQDN anchors that
	// register base-only. Optional.
	LinkedAnsName string `json:"linkedAnsName,omitempty"`

	// LinkedAnchorType reports the linked registration's anchor type
	// ("fqdn", "did", "lei"). Optional but recommended; lets verifiers
	// filter equivalence-graph edges by anchor type without joining
	// against the registrations themselves.
	LinkedAnchorType string `json:"linkedAnchorType,omitempty"`

	// LinkedAnchorResolvedID is the linked registration's canonical
	// anchor identifier (e.g., the LEI string, the DID URI, the FQDN
	// for an FQDN anchor). Optional but recommended for the same
	// reason as LinkedAnchorType.
	LinkedAnchorResolvedID string `json:"linkedAnchorResolvedId,omitempty"`

	// Rationale records why the link is being asserted. The default
	// "operator-asserted-multi-anchor" applies when the operator
	// registered the same operational entity under multiple anchors
	// and is now publishing the cryptographic link. Other values are
	// deployment-specific and not normatively constrained here.
	Rationale string `json:"rationale,omitempty"`
}

// Agent identifies which agent the event refers to.
type Agent struct {
	Host       string `json:"host"`
	Name       string `json:"name"`
	Version    string `json:"version"`
	ProviderID string `json:"providerId,omitempty"`
}

// Attestations captures evidence the RA recorded at the time of the
// event: cert fingerprints, DNS provisioning state, metadata hashes.
// Every field is optional — producers populate what applies to the
// event type.
//
// Shape note — intentional deviation from the reference TL's V1
// RA-attestations schema, which exposes two representations for each
// cert set: a singleton `identityCert` / `serverCert` plus
// rotation-window arrays `validIdentityCerts` / `validServerCerts`.
// We collapse those into single arrays (`identityCerts`,
// `serverCerts`) on the OSS path — a single active cert is a
// one-element array, rotation windows are N-element arrays. See
// CLAUDE.md deviations table. `dnsRecordsProvisioned` likewise
// becomes a typed array of name/data/type records (reference uses a
// `map[string]string`), which is lossy when the RA needs to publish
// more than one record of the same type or record data containing an
// `=` sign.
type Attestations struct {
	DomainValidation      string            `json:"domainValidation,omitempty"`
	DNSRecordsProvisioned []DNSRecord       `json:"dnsRecordsProvisioned,omitempty"`
	IdentityCerts         []CertificateInfo `json:"identityCerts,omitempty"`
	ServerCerts           []CertificateInfo `json:"serverCerts,omitempty"`
	// MetadataHashes carries SHA-256 hex-lowercase digests of
	// artifacts the operator submitted at registration time. The
	// well-known map keys are reserved by ANS_SPEC.md and reused
	// across this package via the constants below
	// (MetadataHashKeyCapabilitiesHash, …).
	//
	// `omitempty` on the map makes the canonical envelope identical
	// for events whose operator submitted no metadata and events
	// whose map happens to be empty. Both serialize without the
	// `metadataHashes` key, keeping leaf-hash stability across the
	// presence/absence boundary.
	MetadataHashes map[string]string `json:"metadataHashes,omitempty"`
}

// Reserved keys for Attestations.MetadataHashes. Values stored in
// the map under these keys are hex-lowercase SHA-256 digests
// (64 lowercase hex chars).
const (
	// MetadataHashKeyCapabilitiesHash is the SHA-256(JCS(agentCardContent))
	// computed at activation per ANS_SPEC.md §A.1. Operators submit the
	// ANS Trust Card body (§A.2 — the document hosted at
	// /.well-known/ans/trust-card.json) on the V2 registration request
	// as `agentCardContent`; the RA hashes it and seals the digest under
	// this key. The AIM later verifies the live hosted Trust Card content
	// against this value.
	//
	// Distinct from any per-endpoint metadataHash on AgentEndpoint, which
	// hashes the protocol-native metadata (e.g., the A2A AgentCard at
	// /.well-known/agent-card.json) rather than the agent-level
	// ANS Trust Card.
	MetadataHashKeyCapabilitiesHash = "capabilitiesHash"
)

// DNSRecord is one DNS record attesting the agent's *production*
// DNS state at event time — the records an independent verifier
// would see if they queried the authoritative nameserver after the
// agent was activated.
//
// What belongs here: `_ans` TXT (discovery), `_ans-badge` TXT
// (badge), TLSA (DANE binding when DNSSEC is enabled), HTTPS/SVCB
// RRs (endpoint discovery), A/AAAA as needed.
//
// What does NOT belong here: ACME challenge records
// (`_acme-challenge.*`). Those are ephemeral validation artifacts
// torn down after domain control is proved; the method used to
// validate is captured separately in `Attestations.DomainValidation`
// (e.g., "ACME-DNS-01"). Logging challenge tokens would both leak
// short-lived secrets and create dangling records the TL claims
// still exist.
//
// `type` is the DNS RR type as a textual token ("TXT", "A", "AAAA",
// "TLSA", "HTTPS", "CAA", "SRV"). `data` is the record data in its
// zone-file text form; keep it raw so verifiers can reconstruct what
// the authoritative nameserver would serve.
type DNSRecord struct {
	Name string `json:"name"`
	Data string `json:"data"`
	Type string `json:"type"`
	// DNSSECVerified is true when the RA's verifier observed the
	// DNSSEC authenticated-data bit on the response that produced
	// this attestation. Only set for TLSA records where a
	// validating resolver chain confirmed the cert-binding; absent
	// on TXT/HTTPS and on TLSA lookups where the chain didn't
	// validate. `omitempty` so the field drops out unless true —
	// matches V1 byte-for-byte when zero.
	DNSSECVerified bool `json:"dnssecVerified,omitempty"`
}

// CertificateInfo describes one certificate by fingerprint + type + expiry.
//
// `fingerprint` is the textual algorithm-prefixed digest ("SHA256:<hex>")
// so verifiers can match without knowing which hash we used.
// `type` is a textual classification ("X509-OV-CLIENT" for identity
// certs, "X509-DV-SERVER" for BYOC server certs, or any operator-
// assigned value). `notAfter` is the cert's validity end in RFC3339.
type CertificateInfo struct {
	Fingerprint string `json:"fingerprint"`
	CertType    string `json:"type"`
	NotAfter    string `json:"notAfter,omitempty"`
}

// Validate returns nil if the envelope has the minimum fields the TL
// requires to index, de-dupe, and sign the event. It does NOT verify
// the producer signature — that's handled by the producer-sig
// verifier upstream.
func (e *Envelope) Validate() error {
	if e == nil {
		return errors.New("event: nil envelope")
	}
	if e.SchemaVersion != SchemaVersion {
		return fmt.Errorf("event: schemaVersion must be %q, got %q", SchemaVersion, e.SchemaVersion)
	}
	if e.Payload == nil {
		return errors.New("event: payload required")
	}
	if e.Payload.LogID == "" {
		return errors.New("event: payload.logId required")
	}
	if e.Payload.Producer == nil {
		return errors.New("event: payload.producer required")
	}
	p := e.Payload.Producer
	if p.KeyID == "" {
		return errors.New("event: payload.producer.keyId required")
	}
	if p.Signature == "" {
		return errors.New("event: payload.producer.signature required")
	}
	if err := p.Event.Validate(); err != nil {
		return err
	}
	return nil
}

// Validate reports whether the inner event has the minimum fields the
// TL expects a producer to populate.
func (ev *Event) Validate() error {
	if ev == nil {
		return errors.New("event: producer.event required")
	}
	if !ev.EventType.IsValid() {
		return fmt.Errorf("event: invalid eventType %q", ev.EventType)
	}
	if ev.AnsID == "" {
		return errors.New("event: ansId required")
	}
	if ev.AnsName == "" {
		return errors.New("event: ansName required")
	}
	if ev.Timestamp == "" {
		return errors.New("event: timestamp required")
	}
	if _, err := time.Parse(time.RFC3339, ev.Timestamp); err != nil {
		return fmt.Errorf("event: timestamp must be RFC3339: %w", err)
	}
	if ev.EventType == TypeEquivalenceLink {
		if ev.Equivalence == nil {
			return errors.New("event: EQUIVALENCE_LINK requires equivalence")
		}
		if ev.Equivalence.LinkedAnsID == "" {
			return errors.New("event: equivalence.linkedAnsId required")
		}
		if ev.Equivalence.LinkedAnsID == ev.AnsID {
			return errors.New("event: equivalence.linkedAnsId must differ from ansId")
		}
		if ev.Agent != nil {
			return errors.New("event: EQUIVALENCE_LINK must not carry agent")
		}
		if ev.Attestations != nil {
			return errors.New("event: EQUIVALENCE_LINK must not carry attestations")
		}
	} else if ev.Equivalence != nil {
		return fmt.Errorf("event: equivalence not allowed for eventType %q", ev.EventType)
	}
	return nil
}

// SigningInput returns the JCS-canonical bytes of the envelope while
// its outer Signature is empty. These are the bytes the TL's
// attestation signer signs; callers must call this before populating
// Signature.
func (e *Envelope) SigningInput() ([]byte, error) {
	if e.Signature != "" {
		return nil, errors.New("event: SigningInput called on already-signed envelope")
	}
	return canonicalize(e)
}

// LeafBytes returns the JCS-canonical bytes of the fully signed
// envelope — i.e., the bytes Tessera appends to the Merkle tree. The
// envelope's outer Signature MUST be populated before calling this;
// otherwise the leaf would be missing its attestation and no verifier
// could recover the TL's signing input.
func (e *Envelope) LeafBytes() ([]byte, error) {
	if e.Signature == "" {
		return nil, errors.New("event: LeafBytes called on unsigned envelope")
	}
	return canonicalize(e)
}

// LeafHash returns the RFC 6962 §2.1 leaf hash of the envelope:
//
//	SHA-256(0x00 || JCS-canonical bytes of the signed envelope)
//
// This matches what Tessera computes for the leaf it just appended,
// and what an offline verifier computes when walking an inclusion
// proof to the root.
func (e *Envelope) LeafHash() ([32]byte, error) {
	leaf, err := e.LeafBytes()
	if err != nil {
		return [32]byte{}, err
	}
	h := sha256.New()
	h.Write([]byte{0x00})
	h.Write(leaf)
	var out [32]byte
	copy(out[:], h.Sum(nil))
	return out, nil
}

// canonicalize is the shared json.Marshal + JCS wrapper.
func canonicalize(v any) ([]byte, error) {
	body, err := json.Marshal(v)
	if err != nil {
		return nil, fmt.Errorf("event: marshal: %w", err)
	}
	return anscrypto.Canonicalize(body)
}

// ----- reference-matching accessors -----
//
// These mirror the reference TL's helpers so call sites don't
// hand-traverse the nested struct and can migrate to a future V2
// envelope by swapping the underlying type. All accessors return
// zero values on missing intermediate pointers — never panic.

// AgentID returns the agent's ansId.
func (e *Envelope) AgentID() string {
	if ev := e.innerEvent(); ev != nil {
		return ev.AnsID
	}
	return ""
}

// AnsName returns the canonical ANS name from the inner event.
func (e *Envelope) AnsName() string {
	if ev := e.innerEvent(); ev != nil {
		return ev.AnsName
	}
	return ""
}

// AgentFQDN returns the agent host (FQDN) from the inner event, or ""
// if the Agent sub-object is missing.
func (e *Envelope) AgentFQDN() string {
	if ev := e.innerEvent(); ev != nil && ev.Agent != nil {
		return ev.Agent.Host
	}
	return ""
}

// EventType returns the inner event's type as a string.
func (e *Envelope) EventType() string {
	if ev := e.innerEvent(); ev != nil {
		return string(ev.EventType)
	}
	return ""
}

// Timestamp returns the producer's RFC3339 timestamp.
func (e *Envelope) Timestamp() string {
	if ev := e.innerEvent(); ev != nil {
		return ev.Timestamp
	}
	return ""
}

// ExpiresAt returns the producer's RFC3339 expiry (badge TTL) or "".
func (e *Envelope) ExpiresAt() string {
	if ev := e.innerEvent(); ev != nil {
		return ev.ExpiresAt
	}
	return ""
}

// LogID returns the TL-assigned logId, or "".
func (e *Envelope) LogID() string {
	if e.Payload != nil {
		return e.Payload.LogID
	}
	return ""
}

// ProducerKeyID returns the kid used by the producer to sign.
func (e *Envelope) ProducerKeyID() string {
	if e.Payload != nil && e.Payload.Producer != nil {
		return e.Payload.Producer.KeyID
	}
	return ""
}

// ProducerSignature returns the detached-JWS the producer signed.
func (e *Envelope) ProducerSignature() string {
	if e.Payload != nil && e.Payload.Producer != nil {
		return e.Payload.Producer.Signature
	}
	return ""
}

// Version returns the on-wire schemaVersion tag ("V2" for this
// package). Exposed so version-agnostic code (sqlite_tl.EventStore,
// badge/audit read handlers) can record and echo the version
// without importing every possible envelope package.
func (e *Envelope) Version() string { return e.SchemaVersion }

func (e *Envelope) innerEvent() *Event {
	if e == nil || e.Payload == nil || e.Payload.Producer == nil {
		return nil
	}
	return e.Payload.Producer.Event
}
